package com.kmzc.dao.xt;

import java.util.List;

import com.kmzc.entity.xt.XtYh;

public interface XtYhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_yh
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_yh
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    int insert(XtYh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_yh
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    XtYh selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_yh
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    List<XtYh> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xt_yh
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    int updateByPrimaryKey(XtYh record);
}