package com.kmzc.entity.xt;

import java.math.BigDecimal;
import java.util.Date;

public class XtCd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.PKID
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.CDMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String cdmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.CDMS
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String cdms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.CDLX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String cdlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.FJCD
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String fjcd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.SFCDX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String sfcdx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.CDTB
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String cdtb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.CDLJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String cdlj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.CDPX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private BigDecimal cdpx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.SFQY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String sfqy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.SFDKFW
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String sfdkfw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_cd.ZHXGSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date zhxgsj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.PKID
     *
     * @return the value of xt_cd.PKID
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.PKID
     *
     * @param pkid the value for xt_cd.PKID
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.CDMC
     *
     * @return the value of xt_cd.CDMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCdmc() {
        return cdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.CDMC
     *
     * @param cdmc the value for xt_cd.CDMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCdmc(String cdmc) {
        this.cdmc = cdmc == null ? null : cdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.CDMS
     *
     * @return the value of xt_cd.CDMS
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCdms() {
        return cdms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.CDMS
     *
     * @param cdms the value for xt_cd.CDMS
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCdms(String cdms) {
        this.cdms = cdms == null ? null : cdms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.CDLX
     *
     * @return the value of xt_cd.CDLX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCdlx() {
        return cdlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.CDLX
     *
     * @param cdlx the value for xt_cd.CDLX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCdlx(String cdlx) {
        this.cdlx = cdlx == null ? null : cdlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.FJCD
     *
     * @return the value of xt_cd.FJCD
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getFjcd() {
        return fjcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.FJCD
     *
     * @param fjcd the value for xt_cd.FJCD
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setFjcd(String fjcd) {
        this.fjcd = fjcd == null ? null : fjcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.SFCDX
     *
     * @return the value of xt_cd.SFCDX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getSfcdx() {
        return sfcdx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.SFCDX
     *
     * @param sfcdx the value for xt_cd.SFCDX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSfcdx(String sfcdx) {
        this.sfcdx = sfcdx == null ? null : sfcdx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.CDTB
     *
     * @return the value of xt_cd.CDTB
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCdtb() {
        return cdtb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.CDTB
     *
     * @param cdtb the value for xt_cd.CDTB
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCdtb(String cdtb) {
        this.cdtb = cdtb == null ? null : cdtb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.CDLJ
     *
     * @return the value of xt_cd.CDLJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCdlj() {
        return cdlj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.CDLJ
     *
     * @param cdlj the value for xt_cd.CDLJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCdlj(String cdlj) {
        this.cdlj = cdlj == null ? null : cdlj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.CDPX
     *
     * @return the value of xt_cd.CDPX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public BigDecimal getCdpx() {
        return cdpx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.CDPX
     *
     * @param cdpx the value for xt_cd.CDPX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCdpx(BigDecimal cdpx) {
        this.cdpx = cdpx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.SFQY
     *
     * @return the value of xt_cd.SFQY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getSfqy() {
        return sfqy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.SFQY
     *
     * @param sfqy the value for xt_cd.SFQY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSfqy(String sfqy) {
        this.sfqy = sfqy == null ? null : sfqy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.SFDKFW
     *
     * @return the value of xt_cd.SFDKFW
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getSfdkfw() {
        return sfdkfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.SFDKFW
     *
     * @param sfdkfw the value for xt_cd.SFDKFW
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSfdkfw(String sfdkfw) {
        this.sfdkfw = sfdkfw == null ? null : sfdkfw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_cd.ZHXGSJ
     *
     * @return the value of xt_cd.ZHXGSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getZhxgsj() {
        return zhxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_cd.ZHXGSJ
     *
     * @param zhxgsj the value for xt_cd.ZHXGSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setZhxgsj(Date zhxgsj) {
        this.zhxgsj = zhxgsj;
    }
}