package com.kmzc.entity.xt;

import java.util.Date;

public class XtYh {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.PKID
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String pkid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.SSJG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String ssjg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.YHMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String yhmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.YHMM
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String yhmm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.YHLX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String yhlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.SFGLY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String sfgly;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.SGRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date sgrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.XB
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String xb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.CSRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date csrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.SFZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String sfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.CSD
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String csd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.LXDZ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String lxdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.YZBM
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String yzbm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.GZDH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String gzdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.YDDH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String yddh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.YX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String yx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.QMZP
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String qmzp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.XL
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String xl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.BYYX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String byyx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.BYRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date byrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.SXZY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String sxzy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.YHZT
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String yhzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.XTFG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String xtfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.TBFG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String tbfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.BZ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.CJRZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String cjrzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.CJRMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String cjrmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.CJSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date cjsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.ZHXGRZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String zhxgrzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.ZHXGRMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String zhxgrmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.ZHXGSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date zhxgsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.DLLXSBCS
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Byte dllxsbcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.ZHYCDLSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date zhycdlsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.shzt
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String shzt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.shr
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String shr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.shsj
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private Date shsj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xt_yh.shyj
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    private String shyj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.PKID
     *
     * @return the value of xt_yh.PKID
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.PKID
     *
     * @param pkid the value for xt_yh.PKID
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.SSJG
     *
     * @return the value of xt_yh.SSJG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getSsjg() {
        return ssjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.SSJG
     *
     * @param ssjg the value for xt_yh.SSJG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSsjg(String ssjg) {
        this.ssjg = ssjg == null ? null : ssjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.YHMC
     *
     * @return the value of xt_yh.YHMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getYhmc() {
        return yhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.YHMC
     *
     * @param yhmc the value for xt_yh.YHMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setYhmc(String yhmc) {
        this.yhmc = yhmc == null ? null : yhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.YHMM
     *
     * @return the value of xt_yh.YHMM
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getYhmm() {
        return yhmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.YHMM
     *
     * @param yhmm the value for xt_yh.YHMM
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setYhmm(String yhmm) {
        this.yhmm = yhmm == null ? null : yhmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.YHLX
     *
     * @return the value of xt_yh.YHLX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getYhlx() {
        return yhlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.YHLX
     *
     * @param yhlx the value for xt_yh.YHLX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setYhlx(String yhlx) {
        this.yhlx = yhlx == null ? null : yhlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.SFGLY
     *
     * @return the value of xt_yh.SFGLY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getSfgly() {
        return sfgly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.SFGLY
     *
     * @param sfgly the value for xt_yh.SFGLY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSfgly(String sfgly) {
        this.sfgly = sfgly == null ? null : sfgly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.SGRQ
     *
     * @return the value of xt_yh.SGRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getSgrq() {
        return sgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.SGRQ
     *
     * @param sgrq the value for xt_yh.SGRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSgrq(Date sgrq) {
        this.sgrq = sgrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.XB
     *
     * @return the value of xt_yh.XB
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.XB
     *
     * @param xb the value for xt_yh.XB
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.CSRQ
     *
     * @return the value of xt_yh.CSRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.CSRQ
     *
     * @param csrq the value for xt_yh.CSRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCsrq(Date csrq) {
        this.csrq = csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.SFZH
     *
     * @return the value of xt_yh.SFZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getSfzh() {
        return sfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.SFZH
     *
     * @param sfzh the value for xt_yh.SFZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSfzh(String sfzh) {
        this.sfzh = sfzh == null ? null : sfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.CSD
     *
     * @return the value of xt_yh.CSD
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCsd() {
        return csd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.CSD
     *
     * @param csd the value for xt_yh.CSD
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCsd(String csd) {
        this.csd = csd == null ? null : csd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.LXDZ
     *
     * @return the value of xt_yh.LXDZ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getLxdz() {
        return lxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.LXDZ
     *
     * @param lxdz the value for xt_yh.LXDZ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setLxdz(String lxdz) {
        this.lxdz = lxdz == null ? null : lxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.YZBM
     *
     * @return the value of xt_yh.YZBM
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.YZBM
     *
     * @param yzbm the value for xt_yh.YZBM
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm == null ? null : yzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.GZDH
     *
     * @return the value of xt_yh.GZDH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getGzdh() {
        return gzdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.GZDH
     *
     * @param gzdh the value for xt_yh.GZDH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setGzdh(String gzdh) {
        this.gzdh = gzdh == null ? null : gzdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.YDDH
     *
     * @return the value of xt_yh.YDDH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getYddh() {
        return yddh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.YDDH
     *
     * @param yddh the value for xt_yh.YDDH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setYddh(String yddh) {
        this.yddh = yddh == null ? null : yddh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.YX
     *
     * @return the value of xt_yh.YX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getYx() {
        return yx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.YX
     *
     * @param yx the value for xt_yh.YX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setYx(String yx) {
        this.yx = yx == null ? null : yx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.QMZP
     *
     * @return the value of xt_yh.QMZP
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getQmzp() {
        return qmzp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.QMZP
     *
     * @param qmzp the value for xt_yh.QMZP
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setQmzp(String qmzp) {
        this.qmzp = qmzp == null ? null : qmzp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.XL
     *
     * @return the value of xt_yh.XL
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getXl() {
        return xl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.XL
     *
     * @param xl the value for xt_yh.XL
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setXl(String xl) {
        this.xl = xl == null ? null : xl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.BYYX
     *
     * @return the value of xt_yh.BYYX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getByyx() {
        return byyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.BYYX
     *
     * @param byyx the value for xt_yh.BYYX
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setByyx(String byyx) {
        this.byyx = byyx == null ? null : byyx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.BYRQ
     *
     * @return the value of xt_yh.BYRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getByrq() {
        return byrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.BYRQ
     *
     * @param byrq the value for xt_yh.BYRQ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setByrq(Date byrq) {
        this.byrq = byrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.SXZY
     *
     * @return the value of xt_yh.SXZY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getSxzy() {
        return sxzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.SXZY
     *
     * @param sxzy the value for xt_yh.SXZY
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setSxzy(String sxzy) {
        this.sxzy = sxzy == null ? null : sxzy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.YHZT
     *
     * @return the value of xt_yh.YHZT
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getYhzt() {
        return yhzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.YHZT
     *
     * @param yhzt the value for xt_yh.YHZT
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setYhzt(String yhzt) {
        this.yhzt = yhzt == null ? null : yhzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.XTFG
     *
     * @return the value of xt_yh.XTFG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getXtfg() {
        return xtfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.XTFG
     *
     * @param xtfg the value for xt_yh.XTFG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setXtfg(String xtfg) {
        this.xtfg = xtfg == null ? null : xtfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.TBFG
     *
     * @return the value of xt_yh.TBFG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getTbfg() {
        return tbfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.TBFG
     *
     * @param tbfg the value for xt_yh.TBFG
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setTbfg(String tbfg) {
        this.tbfg = tbfg == null ? null : tbfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.BZ
     *
     * @return the value of xt_yh.BZ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.BZ
     *
     * @param bz the value for xt_yh.BZ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.CJRZH
     *
     * @return the value of xt_yh.CJRZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCjrzh() {
        return cjrzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.CJRZH
     *
     * @param cjrzh the value for xt_yh.CJRZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCjrzh(String cjrzh) {
        this.cjrzh = cjrzh == null ? null : cjrzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.CJRMC
     *
     * @return the value of xt_yh.CJRMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getCjrmc() {
        return cjrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.CJRMC
     *
     * @param cjrmc the value for xt_yh.CJRMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCjrmc(String cjrmc) {
        this.cjrmc = cjrmc == null ? null : cjrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.CJSJ
     *
     * @return the value of xt_yh.CJSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.CJSJ
     *
     * @param cjsj the value for xt_yh.CJSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setCjsj(Date cjsj) {
        this.cjsj = cjsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.ZHXGRZH
     *
     * @return the value of xt_yh.ZHXGRZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getZhxgrzh() {
        return zhxgrzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.ZHXGRZH
     *
     * @param zhxgrzh the value for xt_yh.ZHXGRZH
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setZhxgrzh(String zhxgrzh) {
        this.zhxgrzh = zhxgrzh == null ? null : zhxgrzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.ZHXGRMC
     *
     * @return the value of xt_yh.ZHXGRMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getZhxgrmc() {
        return zhxgrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.ZHXGRMC
     *
     * @param zhxgrmc the value for xt_yh.ZHXGRMC
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setZhxgrmc(String zhxgrmc) {
        this.zhxgrmc = zhxgrmc == null ? null : zhxgrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.ZHXGSJ
     *
     * @return the value of xt_yh.ZHXGSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getZhxgsj() {
        return zhxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.ZHXGSJ
     *
     * @param zhxgsj the value for xt_yh.ZHXGSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setZhxgsj(Date zhxgsj) {
        this.zhxgsj = zhxgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.DLLXSBCS
     *
     * @return the value of xt_yh.DLLXSBCS
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Byte getDllxsbcs() {
        return dllxsbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.DLLXSBCS
     *
     * @param dllxsbcs the value for xt_yh.DLLXSBCS
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setDllxsbcs(Byte dllxsbcs) {
        this.dllxsbcs = dllxsbcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.ZHYCDLSJ
     *
     * @return the value of xt_yh.ZHYCDLSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getZhycdlsj() {
        return zhycdlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.ZHYCDLSJ
     *
     * @param zhycdlsj the value for xt_yh.ZHYCDLSJ
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setZhycdlsj(Date zhycdlsj) {
        this.zhycdlsj = zhycdlsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.shzt
     *
     * @return the value of xt_yh.shzt
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getShzt() {
        return shzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.shzt
     *
     * @param shzt the value for xt_yh.shzt
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setShzt(String shzt) {
        this.shzt = shzt == null ? null : shzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.shr
     *
     * @return the value of xt_yh.shr
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getShr() {
        return shr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.shr
     *
     * @param shr the value for xt_yh.shr
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setShr(String shr) {
        this.shr = shr == null ? null : shr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.shsj
     *
     * @return the value of xt_yh.shsj
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public Date getShsj() {
        return shsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.shsj
     *
     * @param shsj the value for xt_yh.shsj
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setShsj(Date shsj) {
        this.shsj = shsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xt_yh.shyj
     *
     * @return the value of xt_yh.shyj
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public String getShyj() {
        return shyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xt_yh.shyj
     *
     * @param shyj the value for xt_yh.shyj
     *
     * @mbg.generated Thu Mar 29 16:28:46 CST 2018
     */
    public void setShyj(String shyj) {
        this.shyj = shyj == null ? null : shyj.trim();
    }
}